### ISSUE TITLE
Generating a microservice application and its entities

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-experimental-microservices#6]
When we generate a microservice application, we should not generate its AngularJS side: it should only be used as a back-end REST service.

Then the entities configuration could be reused at the gateway level, so that we generate the correct front-end on the gateway, that will use the back-end REST service.

For example, we would:
- Generate the "Foo" entity on the "app1" back-end application. It would only have the Java back-end.
- Move the ".jhipster/Foo.json" configuration file to the gateway
- On the gateway, use this file to auto-generate the AngularJS application, that uses the back-end service

This could of course be automated and done in one single step.

We still have work to do to have a nice workflow, so that it's as easy to develop a microservices application as a monolith application.

**Comment by rvanrooy** [comment]
Hi @jdubois.

Wouldn't this tightly couple the microservice to the gateway? Removing a microservice would leave artifacts in the gateway. (I'm sure workflow can help with this as well)

What about exposing both  /api and  /res from a microservice, where its own resources can be served? Something like lazy loading (ocLazyLoad) could then import the client side angular modules from the service directly via the gateway, allowing the service to be contained in one app. Alternatively, a list of services can be discovered from the discovery server when the gateway starts.

This could also allow a service to either act as a microservice or full jhipster app (for development etc)

This would also have the potential advantage of activating microservices from the admin page to include in the gateway.

Thanks for your fantastic work.

**Comment by jdubois** [comment]
You are correct @rvanrooy , and I am not 100% happy with what I suggested.

If we could load the JS/CSS/HTML on the fly, that would be great: I guess it's indeed possible, there is a lot of ressources on this subject on Stackoverflow and blogs...

So let's have list those options on this ticket, and then once we have a good solution, let's try to implement it.

**Comment by rvanrooy** [comment]
I'm probably over-thinking this, but here is a bit more detail on how this could work.

In order for the gateway to know which services need to be proxied, and how, I would suggest the gateway expose a method eg. _/serivce-register_  for microservices to register their intent to join the gateway.

for example, app1 starts up with some new configuration details:

``` yaml
jhipster:
  microservice:
    gatewayId: jhiGateway
    type: UI
    contract:
      resources:
        resource_path: /static
        api_path: /api
        bootstrap_module: app1.js
        exposedEntities:
          foo:
            name: foo
            icon: foo-icon
            description: manage foo items
        admin:
          # include information to be included in admin dashbord etc.
        auth:
          roles:
            - ROLE_USER        
```

App1 then connects to the gateway discovered via the discovery server, and sends a "contract" object to the gateway to indicate which services to expose and how. 

possible configuration items:
- `resources` - paths to the various items the gateway may need to know about
- `gatewayId` - the gateway the service should contact when it is started
- `type` - the type of functionality being offered by this service.  UI indicates that the microservice provides its own sub-UI, and the gatway UI should include links to the service at the defined points (other option is : REST) This might not be necessary.
- `contract` - an API exposed by the jhipster gateway
  - `resources` - links to the endpoints exposed by app1
    - `api_path` - the api endpoint (could also be convention over configuration)
    - `resource_path` - static filesharing endpoint
    - `bootstrap_module` - an angular module that provides the routing states and initialization code to lazy load app1's modules, controllers, js, css, and assets. the gateway loads this in the client to bootstrap the microservice functionality.
  - `exposedEntities` - telling the gateway that a link to foo should exist in the entities dropdown. This is a stub that could contain the name, link, icon and description of the entity, so that the gateway UI can display meaningful information in the UI without first having to load the service.
  - `admin` - hooks into the admin dashboard (optional)
  - `auth` - which roles are allowed access to the resource (don't load client side modules if the resource is not authorized to access them)

This will require dynamically configuring the Zuul proxy with new routes as services join and leave, possibly by using @RefreshScope or digging more into Zuul and configuring it programatically as required.

When a service is configured with the microservice configuration, its auth and other subsystems is disabled in favour of the gateway's mechanism. 

For lazy loading, I've had good success integrating [ocLazyLoad](https://github.com/ocombe/ocLazyLoad) with a jhipster app. It works well with ui-router. There are plenty of other options though.

**Comment by jdubois** [comment]
@rvanrooy no your are perfectly right, have a look at the current "gateway": we already have the routes added automatically, and displayed in Zuul, see https://twitter.com/java_hipster/status/686939754697469952

-> so this is in fact quite easy to know all the registered services, and there is an API to have them discovered automatically from the registry

**Comment by deepu105** [comment]
@jdubois this should be easier with the new structure, we can tweak the entity sub gen to do this automatically based on the applicationType shouldnt be very difficult

**Comment by jdubois** [comment]
This is now being tracked at https://github.com/jhipster/generator-jhipster/issues/2987
